// src/data.js

export const MOCK_PRODUCTS = [
  // --- STAPLES & ATTA ---
  {
    id: 1,
    name: "Aashirvaad Shuddh Chakki Atta",
    weight: "5 kg",
    category: "Staples",
    price: 320,
    image: "https://www.bbassets.com/media/uploads/p/l/40127506_9-aashirvaad-shudh-chakki-atta.jpg",
    inStock: true,
  },
  {
    id: 2,
    name: "Fortune Sunlite Refined Sunflower Oil",
    weight: "800 g",
    category: "Staples",
    price: 145,
    image: "https://www.bbassets.com/media/uploads/p/l/274145_17-fortune-sun-lite-sunflower-refined-oil.jpg",
    inStock: true,
  },
  {
    id: 3,
    name: "India Gate Basmati Rice Dubar",
    weight: "1 kg",
    category: "Staples",
    price: 110,
    image: "https://www.bbassets.com/media/uploads/p/l/280154_4-india-gate-basmati-rice-dubar.jpg",
    inStock: false,
  },
  {
    id: 4,
    name: "Tata Salt - Vacuum Evaporated",
    weight: "1 kg",
    category: "Staples",
    price: 28,
    image: "https://www.bbassets.com/media/uploads/p/l/241600_9-tata-salt-iodized.jpg",
    inStock: true,
  },
  {
    id: 5,
    name: "Daawat Rozana Super Basmati Rice",
    weight: "5 kg",
    category: "Staples",
    price: 380,
    image: "https://www.bbassets.com/media/uploads/p/l/40075197_8-daawat-basmati-rice-rozana-super-90.jpg",
    inStock: true,
  },
  {
    id: 31,
    name: "Tata Sampann Unpolished Toor Dal",
    weight: "1 kg",
    category: "Staples",
    price: 175,
    image: "https://www.bbassets.com/media/uploads/p/l/40000291_12-tata-sampann-unpolished-toor-dal-arhar-dal.jpg",
    inStock: true,
  },

  // --- DAIRY & BREAD ---
  {
    id: 6,
    name: "Amul Butter - Pasteurized",
    weight: "100 g",
    category: "Dairy",
    price: 56,
    image: "https://www.bbassets.com/media/uploads/p/l/104860_8-amul-butter-pasteurised.jpg",
    inStock: true,
  },
  {
    id: 7,
    name: "Amul Taaza Fresh Toned Milk",
    weight: "1 L",
    category: "Dairy",
    price: 72,
    image: "https://www.bbassets.com/media/uploads/p/l/40114416_8-amul-taaza-milk.jpg",
    inStock: true,
  },
  {
    id: 8,
    name: "Britannia 100% Whole Wheat Bread",
    weight: "400 g",
    category: "Dairy",
    price: 50,
    image: "https://www.bbassets.com/media/uploads/p/l/40092239_4-britannia-100-whole-wheat-bread.jpg",
    inStock: true,
  },
  {
    id: 9,
    name: "Amul Masti Spiced Buttermilk",
    weight: "200 ml",
    category: "Dairy",
    price: 15,
    image: "https://www.bbassets.com/media/uploads/p/l/161899_9-amul-masti-buttermilk-spice.jpg",
    inStock: false,
  },
  {
    id: 10,
    name: "Amul Cheese Slices",
    weight: "200 g",
    category: "Dairy",
    price: 135,
    image: "https://www.bbassets.com/media/uploads/p/l/104808_9-amul-cheese-slices.jpg",
    inStock: true,
  },
  {
    id: 32,
    name: "Epigamia Greek Yogurt Blueberry",
    weight: "85 g",
    category: "Dairy",
    price: 70,
    image: "https://www.bbassets.com/media/uploads/p/l/40075139_5-epigamia-greek-yogurt-blueberry.jpg",
    inStock: true,
  },

  // --- SNACKS & MUNCHIES ---
  {
    id: 11,
    name: "Maggi Masala Instant Noodles",
    weight: "70 g",
    category: "Snacks",
    price: 14,
    image: "https://www.bbassets.com/media/uploads/p/l/266160_26-maggi-masala-instant-noodles-vegetarian.jpg",
    inStock: false,
  },
  {
    id: 12,
    name: "Lay's India's Magic Masala Chips",
    weight: "50 g",
    category: "Snacks",
    price: 20,
    image: "https://www.bbassets.com/media/uploads/p/l/102750_17-lays-potato-chips-indias-magic-masala.jpg",
    inStock: true,
  },
  {
    id: 13,
    name: "Parle-G Gold Biscuits",
    weight: "1 kg",
    category: "Snacks",
    price: 120,
    image: "https://www.bbassets.com/media/uploads/p/l/40204945_2-parle-g-gold-biscuits.jpg",
    inStock: true,
  },
  {
    id: 14,
    name: "Haldiram's Nagpur Aloo Bhujia",
    weight: "200 g",
    category: "Snacks",
    price: 55,
    image: "https://www.bbassets.com/media/uploads/p/l/263128_3-haldirams-namkeen-aloo-bhujia.jpg",
    inStock: true,
  },
  {
    id: 15,
    name: "Cadbury Dairy Milk Silk",
    weight: "60 g",
    category: "Snacks",
    price: 80,
    image: "https://www.bbassets.com/media/uploads/p/l/100265001-3_35-cadbury-dairy-milk-silk-chocolate-bar.jpg",
    inStock: true,
  },
  {
    id: 33,
    name: "Bikano Bikaneri Bhujia",
    weight: "200 g",
    category: "Snacks",
    price: 65,
    image: "https://www.bbassets.com/media/uploads/p/l/40078505_3-bikano-namkeen-bikaneri-bhujia.jpg",
    inStock: true,
  },

  // --- BEVERAGES ---
  {
    id: 16,
    name: "Bru Instant Coffee",
    weight: "100 g",
    category: "Beverages",
    price: 245,
    image: "https://www.bbassets.com/media/uploads/p/l/266531_22-bru-instant-coffee.jpg",
    inStock: true,
  },
  {
    id: 17,
    name: "Red Label Tea",
    weight: "500 g",
    category: "Beverages",
    price: 310,
    image: "https://www.bbassets.com/media/uploads/p/l/266569_20-red-label-tea.jpg",
    inStock: true,
  },
  {
    id: 18,
    name: "Coca-Cola Soft Drink",
    weight: "750 ml",
    category: "Beverages",
    price: 45,
    image: "https://www.bbassets.com/media/uploads/p/l/251023_11-coca-cola-soft-drink-original-taste.jpg",
    inStock: true,
  },
  {
    id: 19,
    name: "Real Fruit Power Mixed Fruit",
    weight: "1 L",
    category: "Beverages",
    price: 110,
    image: "https://www.bbassets.com/media/uploads/p/l/229922-2_3-real-fruit-power-juice-mixed.jpg",
    inStock: false,
  },
  {
    id: 34,
    name: "Thums Up Soft Drink",
    weight: "1.25 L",
    category: "Beverages",
    price: 75,
    image: "https://www.bbassets.com/media/uploads/p/l/265707_10-thums-up-thums-up-soft-drink.jpg",
    inStock: true,
  },

  // --- HOUSEHOLD CARE ---
  {
    id: 20,
    name: "Surf Excel Easy Wash Detergent",
    weight: "1 kg",
    category: "Household",
    price: 135,
    image: "https://www.bbassets.com/media/uploads/p/l/40101707_12-surf-excel-easy-wash-detergent-powder.jpg",
    inStock: true,
  },
  {
    id: 21,
    name: "Vim Dishwash Bar- Lemon",
    weight: "300 g",
    category: "Household",
    price: 35,
    image: "https://www.bbassets.com/media/uploads/p/l/306160_22-vim-dishwash-bar-lemon.jpg",
    inStock: true,
  },
  {
    id: 22,
    name: "Harpic Toilet Cleaner",
    weight: "500 ml",
    category: "Household",
    price: 105,
    image: "https://www.bbassets.com/media/uploads/p/l/263754_23-harpic-power-plus-disinfectant-toilet-cleaner-liquid-original.jpg",
    inStock: true,
  },
  {
    id: 23,
    name: "Lizol Floor Cleaner - Citrus",
    weight: "500 ml",
    category: "Household",
    price: 115,
    image: "https://www.bbassets.com/media/uploads/p/l/263839_17-lizol-disinfectant-surface-floor-cleaner-liquid-citrus-kills-999-germs.jpg",
    inStock: true,
  },
  {
    id: 35,
    name: "Comfort Morning Fresh After Wash Fabric Conditioner",
    weight: "860 ml",
    category: "Household",
    price: 235,
    image: "https://www.bbassets.com/media/uploads/p/l/230745_19-comfort-after-wash-morning-fresh-fabric-conditioner.jpg",
    inStock: true,
  },

  // --- PERSONAL CARE ---
  {
    id: 24,
    name: "Colgate Strong Teeth Toothpaste",
    weight: "200 g",
    category: "Personal Care",
    price: 115,
    image: "https://www.bbassets.com/media/uploads/p/l/263921_30-colgate-strong-teeth-anticavity-toothpaste-with-amino-shakti-formula-provides-fresher-breath.jpg",
    inStock: true,
  },
  {
    id: 25,
    name: "Dettol Skincare Liquid Handwash",
    weight: "1.3 L",
    category: "Personal Care",
    price: 240,
    image: "https://www.bbassets.com/media/uploads/p/l/40160740_22-dettol-liquid-handwash-skincare-everyday-protection-ph-balanced-moisturising.jpg",
    inStock: true,
  },
  {
    id: 26,
    name: "Dove Almond Cream Beauty Bar",
    weight: "75 g",
    category: "Personal Care",
    price: 58,
    image: "https://www.bbassets.com/media/uploads/p/l/40111422-2_1-dove-bathing-bar-soap-almond-cream-beauty.jpg",
    inStock: false,
  },
  {
    id: 27,
    name: "Head & Shoulders Smooth & Silky",
    weight: "180 ml",
    category: "Personal Care",
    price: 180,
    image: "https://www.bbassets.com/media/uploads/p/l/267846_10-head-shoulders-anti-dandruff-shampoo-smooth-silky-for-dry-damaged-hair.jpg",
    inStock: true,
  },
  {
    id: 28,
    name: "Parachute 100% Pure Coconut Oil",
    weight: "200 ml",
    category: "Personal Care",
    price: 95,
    image: "https://www.bbassets.com/media/uploads/p/l/40130536_4-parachute-pure-coconut-oil.jpg",
    inStock: true,
  },
  {
    id: 29,
    name: "Pears Pure & Gentle Bathing Bar",
    weight: "125 g",
    category: "Personal Care",
    price: 85,
    image: "https://www.bbassets.com/media/uploads/p/l/306189-3_2-pears-pure-gentle-soap-bar.jpg",
    inStock: true,
  },
  {
    id: 30,
    name: "Sunsilk Stunning Black Shine Shampoo",
    weight: "180 ml",
    category: "Personal Care",
    price: 145,
    image: "https://www.bbassets.com/media/uploads/p/l/1200029641_3-sunsilk-stunning-black-shine-shampoo.jpg",
    inStock: true,
  },
  {
    id: 36,
    name: "Gillette Mach 3 Turbo 3-Bladed Refill - With Comfort Gel Bar, Advanced Anti-Friction Coating",
    weight: "4 pcs",
    category: "Personal Care",
    price: 750,
    image: "https://www.bbassets.com/media/uploads/p/l/235214_19-gillette-mach-3-turbo-3-bladed-refill-with-comfort-gel-bar-advanced-anti-friction-coating.jpg",
    inStock: true,
  },

  // --- FRUITS & VEG MOCK (Extra IDs) ---
  {
    id: 37,
    name: "Fresh Potato - Local",
    weight: "1 kg",
    category: "Staples",
    price: 45,
    image: "https://www.bbassets.com/media/uploads/p/l/40048457-5_5-fresho-potato-new-crop.jpg",
    inStock: true,
  },
  {
    id: 38,
    name: "Fresh Onion- Organically Grown",
    weight: "1 kg",
    category: "Staples",
    price: 38,
    image: "https://www.bbassets.com/media/uploads/p/l/40023472-5_2-fresho-onion-organically-grown.jpg",
    inStock: true,
  },
  {
    id: 39,
    name: "Fresh Tomato - Local",
    weight: "500 g",
    category: "Staples",
    price: 25,
    image: "https://www.bbassets.com/media/uploads/p/l/10000203-5_2-fresho-tomato-local.jpg",
    inStock: true,
  },
  {
    id: 40,
    name: "Fresh Ginger",
    weight: "100 g",
    category: "Staples",
    price: 15,
    image: "https://www.jiomart.com/images/product/original/590003531/ginger-indian-200-g-product-images-o590003531-p590003531-1-202408070949.jpg?im=Resize=(420,420)",
    inStock: true,
  }
];

export const MOCK_REQUESTS = [];